version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Athens
    open-pull-requests-limit: 5
    commit-message:
      prefix: "build(deps)"
    labels:
      - dependencies
    groups:
      abaplint:
        patterns:
          - "@abaplint/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    commit-message:
      prefix: "ci(deps)"
    labels:
      - dependencies
    groups:
      actions:
        patterns:
          - "*"
